version: '3.7'
services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./dist:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./docker/php-fpm
        restart: unless-stopped
        ports:
            - 9000:9000
        volumes:
            - ./dist:/var/www/html
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - mariadb_data:/var/lib/mysql
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mariadb
        restart: unless-stopped
        ports:
            - 8080:80
        depends_on:
            - mariadb
volumes:
    mariadb_data:
